name: Node.js CI

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - run: npm test
# This works but leaving out for now to avoid disturbance
#     - name: Play celebration song on Google Home with Spotify
#       # https://developer.spotify.com/console/put-play
#       # uses: fjogeleit/http-request-action@8e939c608aea2d5df19da3e8229cf035f7aa9e4c
#       uses: fjogeleit/http-request-action@v1.8.1
#       with:
#         # Request URL
#         url: https://api.spotify.com/v1/me/player/play?device_id=${{ secrets.SPOTIFY_DEVICE_ID }}
#         # Request Method
#         method: PUT
#         # Content Type
#         contentType: application/json
#         # Request Body as JSON String
#         data: "{\"context_uri\":\"${{ secrets.SPOTIFY_CONTEXT_URI }}\",\"offset\":{\"position\":0},\"position_ms\":0}"
#         # Bearer Authentication Token
#         bearerToken: ${{ secrets.SPOTIFY_PLAYER_API_TOKEN }}
    - name: GitHub API Request
      # You may pin to the exact commit or the version.
      # uses: octokit/request-action@7e93b91076fad3920c29d44eb2a6311d929db3dd
      uses: octokit/request-action@v2.1.0
      with:
        # HTTP Verb + path as shown on https://developer.github.com/v3/
        # TODO: make user/repo dynamic
        route: POST /repos/kriscfoster/actions-experiments/issues/${{github.event.number}}/comments
        # Custom media type in the Accept header
#         body: "{\"body\": \"hi\"}"
        owner: "kriscfoster"
        repo: "actions-experiments"
        issue_number: ${{github.event.number}}
        body: '![image](https://drive.google.com/uc?export=view&id=1Jcv3rzTXwgmJuQgAOkLk4ONAk0J2-eCP)'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
