name: PR Celebration

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
# This works but leaving out for now to avoid disturbance
#     - name: Play celebration song on Google Home with Spotify
#       # https://developer.spotify.com/console/put-play
#       # uses: fjogeleit/http-request-action@8e939c608aea2d5df19da3e8229cf035f7aa9e4c
#       uses: fjogeleit/http-request-action@v1.8.1
#       with:
#         url: https://api.spotify.com/v1/me/player/play?device_id=${{ secrets.SPOTIFY_DEVICE_ID }}
#         method: PUT
#         contentType: application/json
#         data: "{\"context_uri\":\"${{ secrets.SPOTIFY_CONTEXT_URI }}\",\"offset\":{\"position\":0},\"position_ms\":0}"
#         bearerToken: ${{ secrets.SPOTIFY_PLAYER_API_TOKEN }}
    - name: Retrieve celebration picture
      id: retrieve_celebration_picture
      run: |
        echo "::set-output name=id::$(curl https://run.mocky.io/v3/c44c51bb-fd2c-4fab-9901-1e34e91e2c7b | jq .id)"
    - name: Post celebration picture
      uses: octokit/request-action@v2.1.0
      with:
        route: POST /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues/${{ github.event.number }}/comments
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        issue_number: ${{ github.event.number }}
        body: "Tests Passed, it's time to celebrate! :tada::tada::tada:![image](https://drive.google.com/uc?export=view&id=${{ steps.retrieve_celebration_picture.outputs.id }})"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
