name: PR Celebration

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Turn office light on with green
      uses: kriscfoster/tplink-action@v1.4
      with:
        email: ${{ secrets.TPLINK_EMAIL }}
        password: ${{ secrets.TPLINK_PASSWORD }}
        deviceType: "HS100" # currently supported: "HS100"
        deviceId: ${{ secrets.TPLINK_DEVICE_ID }} # this can be the id/alias of the device
        operation: "powerOn" # currently supported: "powerOn", "powerOff", "listDevices"
    - name: Play celebration song with Spotify
      # https://developer.spotify.com/console/put-play
      uses: fjogeleit/http-request-action@v1.8.1
      with:
        url: https://api.spotify.com/v1/me/player/play?device_id=${{ secrets.SPOTIFY_DEVICE_ID }}
        method: PUT
        contentType: application/json
        data: "{\"context_uri\":\"${{ secrets.SPOTIFY_CONTEXT_URI }}\",\"offset\":{\"position\":0},\"position_ms\":0}"
        bearerToken: ${{ secrets.SPOTIFY_PLAYER_API_TOKEN }}
    - name: Enjoy song for 10 seconds
      run: sleep 10s
      shell: bash
    - name: Take celebration picture
      id: retrieve_celebration_picture
      run: |
        echo "::set-output name=id::$(curl -H Authorization:${{ secrets.AUTHORIZATION_TOKEN }} ${{ secrets.PI_ENDPOINT }} | jq .id | tr -d '"')"
    - name: Post celebration picture
      uses: octokit/request-action@v2.1.0
      with:
        route: POST /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/issues/${{ github.event.number }}/comments
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        issue_number: ${{ github.event.number }}
        body: "Tests Passed, it's time to celebrate! :tada::tada::tada:![image](https://drive.google.com/uc?export=view&id=${{ steps.retrieve_celebration_picture.outputs.id }})"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
